"use strict";

/**
 * Central game registry.
 *
 * This is the single source of truth for every game on the platform.
 * The multiplayer system (room manager, socket handlers, handlers index
 * and the browser-side game picker) is generated from this object, so a
 * game ID used in the frontend and the backend can never drift apart.
 *
 * IDs here are the canonical route names used across the whole site
 * (e.g. "/game/snake" -> id "snake", "/game/2048" -> id "2048").
 */
const gameRegistry = {
  snake: {
    id: "snake",
    name: "Snake Rush",
    icon: "🐍",
    logo: "/static/icons/snake.svg",
    banner: "/static/images/games/snake.svg",
    accent: "#39ff14",
    description: "Classic arcade snake on a neon grid.",
    route: "/game/snake",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    mode: "simultaneous",
  },
  memory: {
    id: "memory",
    name: "Memory Pulse",
    icon: "🧠",
    logo: "/static/icons/memory.svg",
    banner: "/static/images/games/memory.svg",
    accent: "#00e5ff",
    description: "Flip cards, match pairs, and race your opponent.",
    route: "/game/memory",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    mode: "simultaneous",
  },
  quiz: {
    id: "quiz",
    name: "Quiz Reactor",
    icon: "❓",
    logo: "/static/icons/quiz.svg",
    banner: "/static/images/games/quiz.svg",
    accent: "#ffb703",
    description: "Fast multiple-choice rounds with per-question timers.",
    route: "/game/quiz",
    minPlayers: 2,
    maxPlayers: 8,
    multiplayer: true,
    mode: "simultaneous",
  },
  tictactoe: {
    id: "tictactoe",
    name: "Tic Tac Toe Grid",
    icon: "⭕",
    logo: "/static/icons/tictactoe.svg",
    banner: "/static/images/games/tictactoe.svg",
    accent: "#ff4d9d",
    description: "Play head-to-head or challenge the AI.",
    route: "/game/tictactoe",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    mode: "turn-based",
  },
  spinwheel: {
    id: "spinwheel",
    name: "Spin the Wheel",
    icon: "🎡",
    logo: "/static/icons/spinwheel.svg",
    banner: "/static/images/games/spinwheel.svg",
    accent: "#c084fc",
    description: "Spin a colorful prize wheel and out-spin your rivals.",
    route: "/game/spinwheel",
    minPlayers: 2,
    maxPlayers: 8,
    multiplayer: true,
    mode: "simultaneous",
  },
  ludo: {
    id: "ludo",
    name: "Ludo Blitz",
    icon: "🎲",
    logo: "/static/icons/ludo.svg",
    banner: "/static/images/games/ludo.svg",
    accent: "#ff6b35",
    description: "Race tokens home in a 2-4 player Ludo showdown.",
    route: "/game/ludo",
    minPlayers: 2,
    maxPlayers: 4,
    multiplayer: true,
    mode: "turn-based",
  },
  chess: {
    id: "chess",
    name: "Neon Chess",
    icon: "♞",
    logo: "/static/icons/chess.svg",
    banner: "/static/images/games/chess.svg",
    accent: "#f0c040",
    description: "Classic chess with legal hints and minimax AI.",
    route: "/game/chess",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    mode: "turn-based",
  },
  "2048": {
    id: "2048",
    name: "2048 Surge",
    icon: "🔢",
    logo: "/static/icons/2048.svg",
    banner: "/static/images/games/2048.svg",
    accent: "#fb923c",
    description: "Merge tiles, chase 2048, and outscore your rival.",
    route: "/game/2048",
    minPlayers: 2,
    maxPlayers: 4,
    multiplayer: true,
    mode: "simultaneous",
  },
  whackamole: {
    id: "whackamole",
    name: "Whack-a-Mole",
    icon: "🐹",
    logo: "/static/icons/whackamole.svg",
    banner: "/static/images/games/whackamole.svg",
    accent: "#4ade80",
    description: "Whack popping moles before the timer ends.",
    route: "/game/whackamole",
    minPlayers: 2,
    maxPlayers: 4,
    multiplayer: true,
    mode: "simultaneous",
  },
  flappy: {
    id: "flappy",
    name: "Flappy Burst",
    icon: "🐤",
    logo: "/static/icons/flappy.svg",
    banner: "/static/images/games/flappy.svg",
    accent: "#38bdf8",
    description: "Flap through pipes in a head-to-head race.",
    route: "/game/flappy",
    minPlayers: 2,
    maxPlayers: 4,
    multiplayer: true,
    mode: "simultaneous",
  },
  breakout: {
    id: "breakout",
    name: "Breakout Neon",
    icon: "🧱",
    logo: "/static/icons/breakout.svg",
    banner: "/static/images/games/breakout.svg",
    accent: "#e879f9",
    description: "Smash bricks, preserve lives, and outlast the opponent.",
    route: "/game/breakout",
    minPlayers: 2,
    maxPlayers: 4,
    multiplayer: true,
    mode: "simultaneous",
  },
  "rps-arena": {
    id: "rps-arena",
    name: "RPS Arena",
    icon: "⚔️",
    logo: "/static/icons/rps-arena.svg",
    banner: "/static/images/games/rps-arena.svg",
    accent: "#ff4d6d",
    description: "Choose your move in secret and defeat your opponent in a rapid duel.",
    route: "/game/rps-arena",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    genre: "Casual",
    mode: "simultaneous-hidden-choice",
  },
  "neon-connect": {
    id: "neon-connect",
    name: "Neon Connect",
    icon: "🔴",
    logo: "/static/icons/neon-connect.svg",
    banner: "/static/images/games/neon-connect.svg",
    accent: "#00e5ff",
    description: "Drop glowing discs and connect four before your opponent.",
    route: "/game/neon-connect",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    genre: "Strategy",
    mode: "turn-based-shared-board",
  },
  "neon-fleet": {
    id: "neon-fleet",
    name: "Neon Fleet",
    icon: "🚢",
    logo: "/static/icons/neon-fleet.svg",
    banner: "/static/images/games/neon-fleet.svg",
    accent: "#38bdf8",
    description: "Deploy your fleet and destroy your opponent before they find you.",
    route: "/game/neon-fleet",
    minPlayers: 2,
    maxPlayers: 2,
    multiplayer: true,
    genre: "Strategy",
    mode: "turn-based-private-board",
  },
  "color-clash": {
    id: "color-clash",
    name: "Color Clash",
    icon: "🃏",
    logo: "/static/icons/color-clash.svg",
    banner: "/static/images/games/color-clash.svg",
    accent: "#c084fc",
    description: "Match colors, numbers and powers in a competitive card showdown.",
    route: "/game/color-clash",
    minPlayers: 2,
    maxPlayers: 4,
    multiplayer: true,
    genre: "Cards",
    mode: "turn-based-private-hand",
  },
};

/**
 * Compact per-game configuration used by the room manager and handlers.
 * Every entry is multiplayer-ready because every game now has a server
 * adapter registered in server/gameHandlers/index.js.
 */
const gameConfig = Object.fromEntries(
  Object.entries(gameRegistry).map(([id, game]) => [
    id,
    {
      title: game.name,
      route: game.route,
      icon: game.icon,
      logo: game.logo,
      banner: game.banner,
      minPlayers: game.minPlayers,
      maxPlayers: game.maxPlayers,
      multiplayerReady: true,
      mode: game.mode,
    },
  ])
);

/** Alternate spellings clients may send (kept for forward compatibility). */
const GAME_ALIASES = {
  "tic-tac-toe": "tictactoe",
  "tick-tac-toe": "tictactoe",
  "2048-surge": "2048",
  rps: "rps-arena",
  "rock-paper-scissors": "rps-arena",
  "connect-four": "neon-connect",
  "connect4": "neon-connect",
  battleship: "neon-fleet",
  uno: "color-clash",
};

function canonicalGameId(value) {
  const id = String(value || "").trim().toLowerCase();
  return GAME_ALIASES[id] || id;
}

module.exports = {
  gameRegistry,
  gameConfig,
  canonicalGameId,
};
