"use strict";

const { loadXml } = require("./configLoader");

const config = loadXml("flappy");
const GRAVITY = Number(config.gravity || 0.38);
const PIPE_GAP = Number(config.pipe_gap || 132);
const PIPE_SPEED = Number(config.pipe_speed || 2.4);
const BIRD_COLOR = String(config.bird_color || "#38bdf8");

const CANVAS_WIDTH = 420;
const CANVAS_HEIGHT = 520;
const PIPE_WIDTH = 66;
const SPAWN_INTERVAL = 95;
const FLAP_VY = -6.4;

/**
 * Server-authoritative Flappy adapter (simultaneous competitive).
 *
 * All players fly through the SAME pipe field: pipes are generated by the
 * server, so every client renders the identical course. Each player
 * controls their own bird. The first bird to crash loses; when a match
 * ends the player with the highest score wins (survivors break ties).
 */
const flappyHandler = {
  gameId: "flappy",
  mode: "simultaneous",
  tickMs: 33,
  roles: ["Player 1", "Player 2"],

  createInitialState() {
    return {
      pipes: [],
      frames: 0,
      playerStates: {},
      finished: false,
      winner: null,
      draw: false,
      startTime: Date.now(),
    };
  },

  assignRoles(room) {
    room.players.forEach((player, index) => {
      player.role = `Player ${index + 1}`;
    });
  },

  firstTurn(room) {
    return null;
  },

  initializeMatch(room) {
    room.gameState.playerStates = {};
    room.players.forEach((player) => {
      room.gameState.playerStates[player.playerNumber] = {
        bird: { x: 110, y: CANVAS_HEIGHT / 2, vy: 0, radius: 14 },
        score: 0,
        alive: true,
      };
    });
  },

  validateAction({ room, player, action }) {
    const type = String(action?.type || "").trim().toLowerCase();
    if (type !== "flap") return { ok: false, error: "Unknown action type for this game." };
    const playerState = room.gameState.playerStates[player.playerNumber];
    if (!playerState || !playerState.alive) return { ok: false, error: "Your bird has crashed." };
    return { ok: true };
  },

  applyAction({ room, player }) {
    room.gameState.playerStates[player.playerNumber].bird.vy = FLAP_VY;
  },

  tick(room) {
    const state = room.gameState;
    if (state.finished) return;

    state.frames += 1;

    // Spawn a shared pipe.
    if (state.frames % SPAWN_INTERVAL === 0) {
      const minY = 90;
      const maxY = CANVAS_HEIGHT - 90;
      const gapY = minY + Math.random() * (maxY - minY);
      state.pipes.push({ x: CANVAS_WIDTH + 20, gapY, passedBy: {} });
    }

    // Advance pipes.
    for (const pipe of state.pipes) pipe.x -= PIPE_SPEED;
    while (state.pipes.length && state.pipes[0].x + PIPE_WIDTH < -30) state.pipes.shift();

    // Advance every bird. Each player scores per pipe they pass; the
    // pass flag is tracked per player so nobody is starved of points.
    for (const [playerNumber, playerState] of Object.entries(state.playerStates)) {
      if (!playerState.alive) continue;

      const bird = playerState.bird;
      bird.vy += GRAVITY;
      bird.y += bird.vy;

      for (const pipe of state.pipes) {
        if (!pipe.passedBy[playerNumber] && pipe.x + PIPE_WIDTH < bird.x) {
          pipe.passedBy[playerNumber] = true;
          playerState.score += 1;
        }
      }

      if (bird.y - bird.radius < 0 || bird.y + bird.radius > CANVAS_HEIGHT) {
        playerState.alive = false;
        continue;
      }

      for (const pipe of state.pipes) {
        const inX = bird.x + bird.radius > pipe.x && bird.x - bird.radius < pipe.x + PIPE_WIDTH;
        const hitTop = bird.y - bird.radius < pipe.gapY - PIPE_GAP / 2;
        const hitBottom = bird.y + bird.radius > pipe.gapY + PIPE_GAP / 2;
        if (inX && (hitTop || hitBottom)) {
          playerState.alive = false;
          break;
        }
      }
    }
  },

  checkGameOver(room) {
    const state = room.gameState;
    if (state.finished) return { finished: true, winner: state.winner, draw: state.draw };

    const entries = Object.entries(state.playerStates);
    const crashed = entries.filter(([, playerState]) => !playerState.alive);
    if (crashed.length === 0) return { finished: false, winner: null, draw: false };

    // Someone crashed: crashed players cannot win. If anyone is still
    // flying, the winner is the best-scoring survivor; if everyone
    // crashed, the highest score wins (draw on equal scores).
    const survivors = entries.filter(([, playerState]) => playerState.alive);
    const pool = survivors.length > 0 ? survivors : entries;
    const ranked = pool
      .map(([playerNumber, playerState]) => ({ playerNumber: Number(playerNumber), score: playerState.score, alive: playerState.alive }))
      .sort((a, b) => b.score - a.score || Number(b.alive) - Number(a.alive));

    const top = ranked[0];
    const second = ranked[1];
    const draw = Boolean(second && second.score === top.score && second.alive === top.alive);

    state.finished = true;
    state.winner = draw ? null : top.playerNumber;
    state.draw = draw;
    return { finished: true, winner: state.winner, draw };
  },

  resetState(room) {
    room.gameState = this.createInitialState();
    this.assignRoles(room);
    this.initializeMatch(room);
  },
};

module.exports = flappyHandler;
